// Convert ISO country code to flag emoji
export function getFlagEmoji(countryCode) {
  if (!countryCode || countryCode.length !== 2) return "";
  const codePoints = countryCode
    .toUpperCase()
    .split("")
    .map((char) => 127397 + char.charCodeAt());
  return String.fromCodePoint(...codePoints);
}

// Track missing timezones for logging
const missingTimezones = new Set();
let hasLoggedSummary = false;

// City to country code mapping (comprehensive)
const cityToCountryMap = {
  // US cities
  New_York: "US",
  Los_Angeles: "US",
  Chicago: "US",
  Denver: "US",
  Phoenix: "US",
  Anchorage: "US",
  Detroit: "US",
  Indianapolis: "US",
  Juneau: "US",
  Louisville: "US",
  Menominee: "US",
  Metlakatla: "US",
  Nome: "US",
  Sitka: "US",
  Yakutat: "US",
  Honolulu: "US",
  Boise: "US",
  Mazatlan: "US",
  Monterrey: "MX",

  // Canada
  Toronto: "CA",
  Vancouver: "CA",
  Winnipeg: "CA",
  Halifax: "CA",
  St_Johns: "CA",
  Edmonton: "CA",
  Calgary: "CA",
  Regina: "CA",
  Yellowknife: "CA",
  Whitehorse: "CA",
  Dawson: "CA",
  Inuvik: "CA",
  Iqaluit: "CA",
  Rainy_River: "CA",
  Resolute: "CA",
  Rankin_Inlet: "CA",
  Thunder_Bay: "CA",
  Swift_Current: "CA",
  Pangnirtung: "CA",

  // Mexico
  Mexico_City: "MX",
  Cancun: "MX",
  Merida: "MX",
  Tijuana: "MX",
  Chihuahua: "MX",
  Ojinaga: "MX",
  Hermosillo: "MX",
  Monterrey: "MX",
  Matamoros: "MX",
  Mazatlan: "MX",

  // Central America
  Guatemala: "GT",
  Belize: "BZ",
  El_Salvador: "SV",
  Tegucigalpa: "HN",
  Managua: "NI",
  San_Jose: "CR",
  Panama: "PA",

  // Caribbean
  Havana: "CU",
  Jamaica: "JM",
  "Port-au-Prince": "HT",
  Santo_Domingo: "DO",
  Puerto_Rico: "PR",
  Bridgetown: "BB",
  Kingston: "JM",
  Nassau: "BS",

  // South America
  Sao_Paulo: "BR",
  Rio_de_Janeiro: "BR",
  Manaus: "BR",
  Recife: "BR",
  Fortaleza: "BR",
  Belem: "BR",
  Brasilia: "BR",
  Campo_Grande: "BR",
  Cuiaba: "BR",
  Buenos_Aires: "AR",
  Cordoba: "AR",
  Mendoza: "AR",
  Jujuy: "AR",
  Catamarca: "AR",
  Santiago: "CL",
  Punta_Arenas: "CL",
  Easter: "CL",
  Lima: "PE",
  Bogota: "CO",
  Caracas: "VE",
  Guayaquil: "EC",
  Quito: "EC",
  Montevideo: "UY",
  Asuncion: "PY",
  La_Paz: "BO",
  Paramaribo: "SR",
  Cayenne: "GF",
  Georgetown: "GY",
  Adak: "US",
  Anguilla: "AI",
  Antigua: "AG",
  Aruba: "AW",
  Barbados: "BB",
  Boa_Vista: "BR",
  Cayman: "KY",
  Ciudad_Juarez: "MX",
  Coral_Harbour: "CA",
  Coyhaique: "CL",
  Curacao: "CW",
  Dominica: "DM",
  Grand_Turk: "TC",
  Grenada: "GD",
  Guadeloupe: "GP",
  Kralendijk: "BQ",
  Lower_Princes: "SX",
  Marigot: "MF",
  Martinique: "MQ",
  Miquelon: "PM",
  Montserrat: "MS",
  Port_of_Spain: "TT",
  Noronha: "BR",
  Porto_Velho: "BR",
  Santarem: "BR",
  St_Barthelemy: "BL",
  St_Kitts: "KN",
  St_Lucia: "LC",
  St_Thomas: "VI",
  St_Vincent: "VC",
  Tortola: "VG",
  La_Rioja: "AR",
  Rio_Gallegos: "AR",
  Salta: "AR",
  San_Juan: "AR",
  San_Luis: "AR",
  Tucuman: "AR",
  Ushuaia: "AR",

  // Greenland & Arctic
  Thule: "GL",
  Godthab: "GL",
  Nuuk: "GL",
  Scoresbysund: "GL",
  Danmarkshavn: "GL",

  // Atlantic
  Bermuda: "BM",
  Azores: "PT",
  Canary: "ES",
  Madeira: "PT",
  Reykjavik: "IS",
  Faroe: "FO",
  Faeroe: "FO",
  South_Georgia: "GS",
  St_Helena: "SH",
  Cape_Verde: "CV",
  Stanley: "FK",

  // Europe
  London: "GB",
  Paris: "FR",
  Berlin: "DE",
  Rome: "IT",
  Milan: "IT",
  Madrid: "ES",
  Barcelona: "ES",
  Amsterdam: "NL",
  Brussels: "BE",
  Vienna: "AT",
  Zurich: "CH",
  Stockholm: "SE",
  Oslo: "NO",
  Copenhagen: "DK",
  Helsinki: "FI",
  Warsaw: "PL",
  Prague: "CZ",
  Budapest: "HU",
  Athens: "GR",
  Lisbon: "PT",
  Dublin: "IE",
  Moscow: "RU",
  Istanbul: "TR",
  Bucharest: "RO",
  Sofia: "BG",
  Zagreb: "HR",
  Ljubljana: "SI",
  Bratislava: "SK",
  Tallinn: "EE",
  Riga: "LV",
  Vilnius: "LT",
  Kiev: "UA",
  Minsk: "BY",
  Chisinau: "MD",
  Belgrade: "RS",
  Podgorica: "ME",
  Sarajevo: "BA",
  Skopje: "MK",
  Tirane: "AL",
  Valletta: "MT",
  Nicosia: "CY",
  Luxembourg: "LU",
  Monaco: "MC",
  San_Marino: "SM",
  Vatican: "VA",
  Gibraltar: "GI",
  Andorra: "AD",
  Guernsey: "GG",
  Jersey: "JE",
  Isle_of_Man: "IM",
  Svalbard: "SJ",
  Longyearbyen: "SJ",
  Busingen: "DE",
  Malta: "MT",
  Vaduz: "LI",

  // Asia
  Tokyo: "JP",
  Shanghai: "CN",
  Beijing: "CN",
  Chongqing: "CN",
  Guangzhou: "CN",
  Urumqi: "CN",
  Kashgar: "CN",
  Hong_Kong: "HK",
  Singapore: "SG",
  Seoul: "KR",
  Dubai: "AE",
  Abu_Dhabi: "AE",
  Kolkata: "IN",
  Mumbai: "IN",
  Delhi: "IN",
  Chennai: "IN",
  Bangalore: "IN",
  Hyderabad: "IN",
  Ahmedabad: "IN",
  Indore: "IN",
  Bangkok: "TH",
  Jakarta: "ID",
  Bali: "ID",
  Makassar: "ID",
  Pontianak: "ID",
  Manila: "PH",
  Kuala_Lumpur: "MY",
  Taipei: "TW",
  Jerusalem: "IL",
  Tel_Aviv: "IL",
  Riyadh: "SA",
  Doha: "QA",
  Qatar: "QA",
  Kuwait: "KW",
  Bahrain: "BH",
  Muscat: "OM",
  Aden: "YE",
  Baghdad: "IQ",
  Tehran: "IR",
  Kabul: "AF",
  Karachi: "PK",
  Islamabad: "PK",
  Dhaka: "BD",
  Colombo: "LK",
  Kathmandu: "NP",
  Thimphu: "BT",
  Yangon: "MM",
  Rangoon: "MM",
  Vientiane: "LA",
  Phnom_Penh: "KH",
  Ho_Chi_Minh: "VN",
  Hanoi: "VN",
  Saigon: "VN",
  Ulaanbaatar: "MN",
  Almaty: "KZ",
  Aqtobe: "KZ",
  Tashkent: "UZ",
  Dushanbe: "TJ",
  Bishkek: "KG",
  Yerevan: "AM",
  Baku: "AZ",
  Tbilisi: "GE",
  Yakutsk: "RU",
  Irkutsk: "RU",
  Novosibirsk: "RU",
  Novokuznetsk: "RU",
  Krasnoyarsk: "RU",
  Vladivostok: "RU",
  Khandyga: "RU",
  Amman: "JO",
  Beirut: "LB",
  Brunei: "BN",
  Calcutta: "IN",
  Damascus: "SY",
  Famagusta: "CY",
  Gaza: "PS",
  Hebron: "PS",
  Kuching: "MY",
  Macau: "MO",

  // Pacific
  Sydney: "AU",
  Melbourne: "AU",
  Brisbane: "AU",
  Perth: "AU",
  Adelaide: "AU",
  Darwin: "AU",
  Hobart: "AU",
  Canberra: "AU",
  Eucla: "AU",
  Lord_Howe: "AU",
  Broken_Hill: "AU",
  Auckland: "NZ",
  Wellington: "NZ",
  Christchurch: "NZ",
  Chatham: "NZ",
  Fiji: "FJ",
  Port_Moresby: "PG",
  Noumea: "NC",
  Guam: "GU",
  Wake: "UM",
  Midway: "UM",
  Honolulu: "US",
  Apia: "WS",
  "Nuku'alofa": "TO",
  Pago_Pago: "AS",
  Pitcairn: "PN",
  Palau: "PW",
  Majuro: "MH",
  Kwajalein: "MH",
  Bougainville: "PG",
  Fakaofo: "TK",
  Funafuti: "TV",
  Galapagos: "EC",
  Kiritimati: "KI",
  Nauru: "NR",
  Niue: "NU",
  Ponape: "FM",
  Pohnpei: "FM",
  Rarotonga: "CK",
  Saipan: "MP",
  Tongatapu: "TO",
  Truk: "FM",
  Wallis: "WF",

  // Africa
  Cairo: "EG",
  Johannesburg: "ZA",
  Lagos: "NG",
  Nairobi: "KE",
  Casablanca: "MA",
  Addis_Ababa: "ET",
  Accra: "GH",
  Dar_es_Salaam: "TZ",
  Kampala: "UG",
  Kigali: "RW",
  Algiers: "DZ",
  Tunis: "TN",
  Tripoli: "LY",
  Khartoum: "SD",
  Dakar: "SN",
  Abidjan: "CI",
  Luanda: "AO",
  Lusaka: "ZM",
  Harare: "ZW",
  Gaborone: "BW",
  Maputo: "MZ",
  Antananarivo: "MG",
  Port_Louis: "MU",
  Mogadishu: "SO",
  Kinshasa: "CD",
  Lubumbashi: "CD",
  Douala: "CM",
  Yaounde: "CM",
  Asmera: "ER",
  Asmara: "ER",
  Banjul: "GM",
  Bissau: "GW",
  Bujumbura: "BI",
  Ceuta: "ES",
  El_Aaiun: "EH",
  Freetown: "SL",
  Monrovia: "LR",
  "Porto-Novo": "BJ",
  Sao_Tome: "ST",

  // Antarctica
  McMurdo: "AQ",
  Palmer: "AQ",
  Rothera: "AQ",
  Syowa: "AQ",
  Mawson: "AQ",
  Davis: "AQ",
  Casey: "AQ",
  Vostok: "AQ",
  DumontDUrville: "AQ",
  Troll: "AQ",
  Macquarie: "AU",

  // Atlantic & Indian Ocean
  Cape_Verde: "CV",
  Stanley: "FK",
  Mayotte: "YT",
};

// Map timezone to country code
export function getCountryCodeFromTimezone(timeZone) {
  if (!timeZone) return null;

  // Common timezone to country code mappings
  const timezoneMap = {
    // Americas
    "America/New_York": "US",
    "America/Chicago": "US",
    "America/Denver": "US",
    "America/Los_Angeles": "US",
    "America/Phoenix": "US",
    "America/Anchorage": "US",
    "America/Detroit": "US",
    "America/Indiana/Indianapolis": "US",
    "America/Juneau": "US",
    "America/Kentucky/Louisville": "US",
    "America/North_Dakota/Center": "US",
    "America/Menominee": "US",
    "America/Metlakatla": "US",
    "America/Nome": "US",
    "America/Sitka": "US",
    "America/Yakutat": "US",
    "America/Toronto": "CA",
    "America/Vancouver": "CA",
    "America/Winnipeg": "CA",
    "America/Halifax": "CA",
    "America/St_Johns": "CA",
    "America/Edmonton": "CA",
    "America/Calgary": "CA",
    "America/Regina": "CA",
    "America/Yellowknife": "CA",
    "America/Whitehorse": "CA",
    "America/Dawson": "CA",
    "America/Inuvik": "CA",
    "America/Iqaluit": "CA",
    "America/Rainy_River": "CA",
    "America/Resolute": "CA",
    "America/Rankin_Inlet": "CA",
    "America/Thunder_Bay": "CA",
    "America/Swift_Current": "CA",
    "America/Pangnirtung": "CA",
    "America/Blanc-Sablon": "CA",
    "America/Atikokan": "CA",
    "America/Cambridge_Bay": "CA",
    "America/Creston": "CA",
    "America/Dawson_Creek": "CA",
    "America/Fort_Nelson": "CA",
    "America/Glace_Bay": "CA",
    "America/Goose_Bay": "CA",
    "America/Moncton": "CA",
    "America/Shiprock": "US",
    "America/Boise": "US",
    "America/Fort_Wayne": "US",
    "America/Indiana/Knox": "US",
    "America/Indiana/Marengo": "US",
    "America/Indiana/Petersburg": "US",
    "America/Indiana/Tell_City": "US",
    "America/Indiana/Vevay": "US",
    "America/Indiana/Vincennes": "US",
    "America/Indiana/Winamac": "US",
    "America/Kentucky/Monticello": "US",
    "America/North_Dakota/Beulah": "US",
    "America/North_Dakota/New_Salem": "US",
    "America/Mexico_City": "MX",
    "America/Cancun": "MX",
    "America/Merida": "MX",
    "America/Monterrey": "MX",
    "America/Tijuana": "MX",
    "America/Chihuahua": "MX",
    "America/Ojinaga": "MX",
    "America/Hermosillo": "MX",
    "America/Matamoros": "MX",
    "America/Mazatlan": "MX",
    "America/Bahia_Banderas": "MX",
    "America/Sao_Paulo": "BR",
    "America/Rio_Branco": "BR",
    "America/Manaus": "BR",
    "America/Eirunepe": "BR",
    "America/Recife": "BR",
    "America/Fortaleza": "BR",
    "America/Belem": "BR",
    "America/Cuiaba": "BR",
    "America/Campo_Grande": "BR",
    "America/Araguaina": "BR",
    "America/Maceio": "BR",
    "America/Bahia": "BR",
    "America/Boa_Vista": "BR",
    "America/Noronha": "BR",
    "America/Porto_Velho": "BR",
    "America/Santarem": "BR",
    "America/Adak": "US",
    "America/Anguilla": "AI",
    "America/Antigua": "AG",
    "America/Aruba": "AW",
    "America/Barbados": "BB",
    "America/Cayman": "KY",
    "America/Ciudad_Juarez": "MX",
    "America/Coral_Harbour": "CA",
    "America/Coyhaique": "CL",
    "America/Curacao": "CW",
    "America/Dominica": "DM",
    "America/Grand_Turk": "TC",
    "America/Grenada": "GD",
    "America/Guadeloupe": "GP",
    "America/Kralendijk": "BQ",
    "America/Lower_Princes": "SX",
    "America/Marigot": "MF",
    "America/Martinique": "MQ",
    "America/Miquelon": "PM",
    "America/Montserrat": "MS",
    "America/Port_of_Spain": "TT",
    "America/St_Barthelemy": "BL",
    "America/St_Kitts": "KN",
    "America/St_Lucia": "LC",
    "America/St_Thomas": "VI",
    "America/St_Vincent": "VC",
    "America/Tortola": "VG",
    "America/Argentina/La_Rioja": "AR",
    "America/Argentina/Rio_Gallegos": "AR",
    "America/Argentina/Salta": "AR",
    "America/Argentina/San_Juan": "AR",
    "America/Argentina/San_Luis": "AR",
    "America/Argentina/Tucuman": "AR",
    "America/Argentina/Ushuaia": "AR",
    "America/Buenos_Aires": "AR",
    "America/Cordoba": "AR",
    "America/Mendoza": "AR",
    "America/Jujuy": "AR",
    "America/Catamarca": "AR",
    "America/Rosario": "AR",
    "America/Santiago": "CL",
    "America/Punta_Arenas": "CL",
    "America/Easter": "CL",
    "America/Lima": "PE",
    "America/Bogota": "CO",
    "America/Caracas": "VE",
    "America/Guayaquil": "EC",
    "America/Quito": "EC",
    "America/Guyana": "GY",
    "America/Paramaribo": "SR",
    "America/Cayenne": "GF",
    "America/La_Paz": "BO",
    "America/Montevideo": "UY",
    "America/Asuncion": "PY",
    "America/Belize": "BZ",
    // Greenland (part of Denmark, uses GL flag)
    "America/Thule": "GL",
    "America/Godthab": "GL",
    "America/Nuuk": "GL",
    "America/Scoresbysund": "GL",
    "America/Danmarkshavn": "GL",
    // Atlantic timezones
    "Atlantic/Thule": "GL",
    "Atlantic/Bermuda": "BM",
    "Atlantic/Azores": "PT",
    "Atlantic/Canary": "ES",
    "Atlantic/Madeira": "PT",
    "Atlantic/Reykjavik": "IS",
    "Atlantic/Faroe": "FO",
    "Atlantic/Faeroe": "FO",
    "Atlantic/Cape_Verde": "CV",
    "Atlantic/Stanley": "FK",
    // Antarctica and other territories
    "Antarctica/McMurdo": "AQ",
    "Antarctica/Palmer": "AQ",
    "Antarctica/Rothera": "AQ",
    "Antarctica/Syowa": "AQ",
    "Antarctica/Mawson": "AQ",
    "Antarctica/Davis": "AQ",
    "Antarctica/Casey": "AQ",
    "Antarctica/Vostok": "AQ",
    "Antarctica/DumontDUrville": "AQ",
    "Antarctica/Troll": "AQ",
    "Antarctica/Macquarie": "AU",
    // Europe
    "Europe/London": "GB",
    "Europe/Paris": "FR",
    "Europe/Berlin": "DE",
    "Europe/Rome": "IT",
    "Europe/Madrid": "ES",
    "Europe/Amsterdam": "NL",
    "Europe/Brussels": "BE",
    "Europe/Vienna": "AT",
    "Europe/Zurich": "CH",
    "Europe/Stockholm": "SE",
    "Europe/Oslo": "NO",
    "Europe/Copenhagen": "DK",
    "Europe/Helsinki": "FI",
    "Europe/Warsaw": "PL",
    "Europe/Prague": "CZ",
    "Europe/Budapest": "HU",
    "Europe/Athens": "GR",
    "Europe/Lisbon": "PT",
    "Europe/Dublin": "IE",
    "Europe/Moscow": "RU",
    "Europe/Kiev": "UA",
    "Europe/Simferopol": "UA",
    "Europe/Uzhgorod": "UA",
    "Europe/Zaporozhye": "UA",
    "Europe/Kaliningrad": "RU",
    "Europe/Samara": "RU",
    "Europe/Volgograd": "RU",
    "Europe/Saratov": "RU",
    "Europe/Astrakhan": "RU",
    "Europe/Kirov": "RU",
    "Europe/Izhevsk": "RU",
    "Europe/Ulyanovsk": "RU",
    "Europe/Yekaterinburg": "RU",
    "Europe/Omsk": "RU",
    "Europe/Novosibirsk": "RU",
    "Europe/Barnaul": "RU",
    "Europe/Tomsk": "RU",
    "Europe/Krasnoyarsk": "RU",
    "Europe/Irkutsk": "RU",
    "Europe/Chita": "RU",
    "Europe/Yakutsk": "RU",
    "Europe/Vladivostok": "RU",
    "Europe/Magadan": "RU",
    "Europe/Sakhalin": "RU",
    "Europe/Srednekolymsk": "RU",
    "Europe/Kamchatka": "RU",
    "Europe/Istanbul": "TR",
    "Europe/Bucharest": "RO",
    "Europe/Sofia": "BG",
    "Europe/Zagreb": "HR",
    "Europe/Ljubljana": "SI",
    "Europe/Bratislava": "SK",
    "Europe/Tallinn": "EE",
    "Europe/Riga": "LV",
    "Europe/Vilnius": "LT",
    "Europe/Belgrade": "RS",
    "Europe/Podgorica": "ME",
    "Europe/Sarajevo": "BA",
    "Europe/Skopje": "MK",
    "Europe/Tirane": "AL",
    "Europe/Valletta": "MT",
    "Europe/Nicosia": "CY",
    "Europe/Chisinau": "MD",
    "Europe/Minsk": "BY",
    "Europe/Luxembourg": "LU",
    "Europe/Monaco": "MC",
    "Europe/San_Marino": "SM",
    "Europe/Vatican": "VA",
    "Europe/Gibraltar": "GI",
    "Europe/Andorra": "AD",
    "Europe/Guernsey": "GG",
    "Europe/Jersey": "JE",
    "Europe/Isle_of_Man": "IM",
    "Europe/Mariehamn": "AX",
    "Europe/Longyearbyen": "SJ",
    "Europe/Busingen": "DE",
    "Europe/Malta": "MT",
    "Europe/Vaduz": "LI",
    // Asia
    "Asia/Tokyo": "JP",
    "Asia/Shanghai": "CN",
    "Asia/Hong_Kong": "HK",
    "Asia/Singapore": "SG",
    "Asia/Seoul": "KR",
    "Asia/Dubai": "AE",
    "Asia/Kolkata": "IN",
    "Asia/Bangkok": "TH",
    "Asia/Jakarta": "ID",
    "Asia/Manila": "PH",
    "Asia/Kuala_Lumpur": "MY",
    "Asia/Taipei": "TW",
    "Asia/Jerusalem": "IL",
    "Asia/Riyadh": "SA",
    "Asia/Doha": "QA",
    "Asia/Kuwait": "KW",
    "Asia/Bahrain": "BH",
    "Asia/Yerevan": "AM",
    "Asia/Baku": "AZ",
    "Asia/Tbilisi": "GE",
    "Asia/Yekaterinburg": "RU",
    "Asia/Omsk": "RU",
    "Asia/Novosibirsk": "RU",
    "Asia/Barnaul": "RU",
    "Asia/Tomsk": "RU",
    "Asia/Krasnoyarsk": "RU",
    "Asia/Irkutsk": "RU",
    "Asia/Chita": "RU",
    "Asia/Yakutsk": "RU",
    "Asia/Vladivostok": "RU",
    "Asia/Magadan": "RU",
    "Asia/Sakhalin": "RU",
    "Asia/Srednekolymsk": "RU",
    "Asia/Kamchatka": "RU",
    "Asia/Anadyr": "RU",
    "Asia/Ust-Nera": "RU",
    "Asia/Khandyga": "RU",
    "Asia/Novokuznetsk": "RU",
    "Asia/Amman": "JO",
    "Asia/Beirut": "LB",
    "Asia/Brunei": "BN",
    "Asia/Calcutta": "IN",
    "Asia/Damascus": "SY",
    "Asia/Famagusta": "CY",
    "Asia/Gaza": "PS",
    "Asia/Hebron": "PS",
    "Asia/Kuching": "MY",
    "Asia/Macau": "MO",
    "Asia/Qatar": "QA",
    "Asia/Saigon": "VN",
    "Asia/Aqtobe": "KZ",
    "Asia/Aqtau": "KZ",
    "Asia/Atyrau": "KZ",
    "Asia/Oral": "KZ",
    "Asia/Qostanay": "KZ",
    "Asia/Qyzylorda": "KZ",
    "Asia/Almaty": "KZ",
    "Asia/Dushanbe": "TJ",
    "Asia/Ashgabat": "TM",
    "Asia/Tashkent": "UZ",
    "Asia/Samarkand": "UZ",
    "Asia/Bishkek": "KG",
    "Asia/Dhaka": "BD",
    "Asia/Dili": "TL",
    "Asia/Jayapura": "ID",
    "Asia/Pontianak": "ID",
    "Asia/Makassar": "ID",
    "Asia/Pyongyang": "KP",
    "Asia/Urumqi": "CN",
    "Asia/Kashgar": "CN",
    "Asia/Chongqing": "CN",
    "Asia/Harbin": "CN",
    "Asia/Kathmandu": "NP",
    "Asia/Katmandu": "NP",
    "Asia/Thimphu": "BT",
    "Asia/Colombo": "LK",
    "Asia/Yangon": "MM",
    "Asia/Rangoon": "MM",
    "Asia/Vientiane": "LA",
    "Asia/Phnom_Penh": "KH",
    "Asia/Ho_Chi_Minh": "VN",
    "Asia/Hanoi": "VN",
    "Asia/Ulaanbaatar": "MN",
    "Asia/Hovd": "MN",
    "Asia/Choibalsan": "MN",
    // Oceania
    "Australia/Sydney": "AU",
    "Australia/Melbourne": "AU",
    "Australia/Brisbane": "AU",
    "Australia/Perth": "AU",
    "Australia/Adelaide": "AU",
    "Australia/Darwin": "AU",
    "Australia/Hobart": "AU",
    "Australia/Canberra": "AU",
    "Australia/Currie": "AU",
    "Australia/Eucla": "AU",
    "Australia/Lord_Howe": "AU",
    "Australia/Lindeman": "AU",
    "Australia/Broken_Hill": "AU",
    "Pacific/Auckland": "NZ",
    "Pacific/Chatham": "NZ",
    "Pacific/Wellington": "NZ",
    "Pacific/Christchurch": "NZ",
    "Pacific/Honolulu": "US",
    "Pacific/Fiji": "FJ",
    "Pacific/Port_Moresby": "PG",
    "Pacific/Noumea": "NC",
    "Pacific/Guam": "GU",
    "Pacific/Wake": "UM",
    "Pacific/Midway": "UM",
    "Pacific/Apia": "WS",
    "Pacific/Nuku'alofa": "TO",
    "Pacific/Pago_Pago": "AS",
    "Pacific/Pitcairn": "PN",
    "Pacific/Palau": "PW",
    "Pacific/Majuro": "MH",
    "Pacific/Kwajalein": "MH",
    "Pacific/Tahiti": "PF",
    "Pacific/Marquesas": "PF",
    "Pacific/Gambier": "PF",
    "Pacific/Enderbury": "KI",
    "Pacific/Tarawa": "KI",
    "Pacific/Efate": "VU",
    "Pacific/Guadalcanal": "SB",
    "Pacific/Norfolk": "NF",
    "Pacific/Chuuk": "FM",
    "Pacific/Pohnpei": "FM",
    "Pacific/Kosrae": "FM",
    "Pacific/Bougainville": "PG",
    "Pacific/Fakaofo": "TK",
    "Pacific/Funafuti": "TV",
    "Pacific/Galapagos": "EC",
    "Pacific/Kiritimati": "KI",
    "Pacific/Nauru": "NR",
    "Pacific/Niue": "NU",
    "Pacific/Ponape": "FM",
    "Pacific/Rarotonga": "CK",
    "Pacific/Saipan": "MP",
    "Pacific/Tongatapu": "TO",
    "Pacific/Truk": "FM",
    "Pacific/Wallis": "WF",
    // Africa
    "Africa/Cairo": "EG",
    "Africa/Johannesburg": "ZA",
    "Africa/Lagos": "NG",
    "Africa/Nairobi": "KE",
    "Africa/Casablanca": "MA",
    "Africa/Addis_Ababa": "ET",
    "Africa/Accra": "GH",
    "Africa/Dar_es_Salaam": "TZ",
    "Africa/Kampala": "UG",
    "Africa/Kigali": "RW",
    "Africa/Algiers": "DZ",
    "Africa/Tunis": "TN",
    "Africa/Tripoli": "LY",
    "Africa/Khartoum": "SD",
    "Africa/Dakar": "SN",
    "Africa/Abidjan": "CI",
    "Africa/Luanda": "AO",
    "Africa/Lusaka": "ZM",
    "Africa/Harare": "ZW",
    "Africa/Gaborone": "BW",
    "Africa/Maputo": "MZ",
    "Africa/Antananarivo": "MG",
    "Africa/Port_Louis": "MU",
    "Africa/Mogadishu": "SO",
    "Africa/Kinshasa": "CD",
    "Africa/Lubumbashi": "CD",
    "Africa/Douala": "CM",
    "Africa/Yaounde": "CM",
    "Africa/Bangui": "CF",
    "Africa/Ndjamena": "TD",
    "Africa/Brazzaville": "CG",
    "Africa/Malabo": "GQ",
    "Africa/Libreville": "GA",
    "Africa/Windhoek": "NA",
    "Africa/Juba": "SS",
    "Africa/Asmara": "ER",
    "Africa/Asmera": "ER",
    "Africa/Banjul": "GM",
    "Africa/Bissau": "GW",
    "Africa/Bujumbura": "BI",
    "Africa/Ceuta": "ES",
    "Africa/El_Aaiun": "EH",
    "Africa/Freetown": "SL",
    "Africa/Monrovia": "LR",
    "Africa/Porto-Novo": "BJ",
    "Africa/Sao_Tome": "ST",
    "Africa/Djibouti": "DJ",
    "Africa/Conakry": "GN",
    "Africa/Bamako": "ML",
    "Africa/Ouagadougou": "BF",
    "Africa/Niamey": "NE",
    "Africa/Nouakchott": "MR",
    "Africa/Lome": "TG",
    "Africa/Mbabane": "SZ",
    "Africa/Lesotho": "LS",
    "Africa/Maseru": "LS",
    "Africa/Blantyre": "MW",
    "Africa/Lilongwe": "MW",
    "Indian/Mauritius": "MU",
    "Indian/Reunion": "RE",
    "Indian/Seychelles": "SC",
    "Indian/Comoro": "KM",
    "Indian/Maldives": "MV",
    "Indian/Mahe": "SC",
    "Indian/Kerguelen": "TF",
    "Indian/Chagos": "IO",
    "Indian/Christmas": "CX",
    "Indian/Cocos": "CC",
    "Indian/Mayotte": "YT",
  };

  // Check direct mapping first
  if (timezoneMap[timeZone]) {
    return timezoneMap[timeZone];
  }

  // Try to infer from timezone prefix
  const parts = timeZone.split("/");
  if (parts.length >= 2) {
    const continent = parts[0];
    let city = parts[parts.length - 1]; // Use last part in case of nested paths like America/Indiana/Indianapolis

    // Handle nested paths like America/Indiana/Indianapolis
    if (parts.length > 2) {
      city = parts[parts.length - 1];
    }

    // First, try direct city mapping
    if (cityToCountryMap[city]) {
      return cityToCountryMap[city];
    }

    // Try case-insensitive exact match
    const cityLower = city.toLowerCase();
    for (const [cityName, countryCode] of Object.entries(cityToCountryMap)) {
      if (cityName.toLowerCase() === cityLower) {
        return countryCode;
      }
    }

    // Try partial matches for cities with variations (e.g., "Indianapolis" matches "Indianapolis")
    for (const [cityName, countryCode] of Object.entries(cityToCountryMap)) {
      const cityNameLower = cityName.toLowerCase();
      if (cityLower.includes(cityNameLower) || cityNameLower.includes(cityLower)) {
        // Make sure it's a reasonable match (not just a single letter)
        if (cityNameLower.length >= 3 || cityLower.length >= 3) {
          return countryCode;
        }
      }
    }

    // Handle nested paths - check the middle part too (e.g., America/Indiana/Indianapolis)
    if (parts.length > 2) {
      const middlePart = parts[parts.length - 2];
      for (const [cityName, countryCode] of Object.entries(cityToCountryMap)) {
        if (
          middlePart.toLowerCase().includes(cityName.toLowerCase()) ||
          cityName.toLowerCase().includes(middlePart.toLowerCase())
        ) {
          if (cityName.length >= 3 || middlePart.length >= 3) {
            return countryCode;
          }
        }
      }
    }

    // Continent-based mappings for common countries
    const continentCountryMap = {
      America: {
        US: [
          "New_York",
          "Los_Angeles",
          "Chicago",
          "Denver",
          "Phoenix",
          "Anchorage",
          "Detroit",
          "Indianapolis",
          "Juneau",
          "Louisville",
          "Menominee",
          "Metlakatla",
          "Nome",
          "Sitka",
          "Yakutat",
          "Honolulu",
          "Boise",
          "Mazatlan",
        ],
        CA: [
          "Toronto",
          "Vancouver",
          "Winnipeg",
          "Halifax",
          "St_Johns",
          "Edmonton",
          "Calgary",
          "Regina",
          "Yellowknife",
          "Whitehorse",
          "Dawson",
          "Inuvik",
          "Iqaluit",
        ],
        MX: ["Mexico_City", "Cancun", "Merida", "Monterrey", "Tijuana"],
        BR: ["Sao_Paulo", "Rio_de_Janeiro", "Manaus", "Recife", "Fortaleza"],
        AR: ["Buenos_Aires", "Cordoba", "Mendoza"],
        CL: ["Santiago"],
        PE: ["Lima"],
        CO: ["Bogota"],
        VE: ["Caracas"],
        PA: ["Panama"],
        CR: ["Costa_Rica"],
        GT: ["Guatemala"],
        SV: ["El_Salvador"],
        HN: ["Tegucigalpa"],
        NI: ["Managua"],
        CU: ["Havana"],
        JM: ["Jamaica"],
        HT: ["Port-au-Prince"],
        DO: ["Santo_Domingo"],
        PR: ["Puerto_Rico"],
        EC: ["Guayaquil", "Quito"],
        UY: ["Montevideo"],
        PY: ["Asuncion"],
        GL: ["Thule", "Godthab", "Nuuk", "Scoresbysund", "Danmarkshavn"], // Greenland
        BM: ["Bermuda"],
        FO: ["Faroe"],
        IS: ["Reykjavik"],
        AQ: ["McMurdo", "Palmer", "Rothera", "Syowa", "Mawson", "Davis", "Casey", "Vostok", "DumontDUrville", "Troll"], // Antarctica
      },
      Atlantic: {
        GL: ["Thule"],
        BM: ["Bermuda"],
        PT: ["Azores", "Madeira"],
        ES: ["Canary"],
        IS: ["Reykjavik"],
        FO: ["Faroe"],
        DK: ["Nuuk"], // Sometimes listed in Atlantic
      },
      Antarctica: {
        AQ: ["McMurdo", "Palmer", "Rothera", "Syowa", "Mawson", "Davis", "Casey", "Vostok", "DumontDUrville", "Troll"],
        NZ: ["McMurdo"], // McMurdo Station is a US/NZ research station
      },
      Europe: {
        GL: ["Nuuk"], // Sometimes listed under Europe
        GB: ["London"],
        FR: ["Paris"],
        DE: ["Berlin"],
        IT: ["Rome", "Milan"],
        ES: ["Madrid", "Barcelona"],
        NL: ["Amsterdam"],
        BE: ["Brussels"],
        AT: ["Vienna"],
        CH: ["Zurich"],
        SE: ["Stockholm"],
        NO: ["Oslo"],
        DK: ["Copenhagen"],
        FI: ["Helsinki"],
        PL: ["Warsaw"],
        CZ: ["Prague"],
        HU: ["Budapest"],
        GR: ["Athens"],
        PT: ["Lisbon"],
        IE: ["Dublin"],
        RU: ["Moscow"],
        TR: ["Istanbul"],
        RO: ["Bucharest"],
        BG: ["Sofia"],
        HR: ["Zagreb"],
        SI: ["Ljubljana"],
        SK: ["Bratislava"],
        EE: ["Tallinn"],
        LV: ["Riga"],
        LT: ["Vilnius"],
      },
      Asia: {
        JP: ["Tokyo"],
        CN: ["Shanghai", "Beijing", "Chongqing", "Guangzhou"],
        HK: ["Hong_Kong"],
        SG: ["Singapore"],
        KR: ["Seoul"],
        AE: ["Dubai", "Abu_Dhabi"],
        IN: ["Kolkata", "Mumbai", "Delhi", "Chennai", "Bangalore", "Hyderabad"],
        TH: ["Bangkok"],
        ID: ["Jakarta", "Bali", "Makassar"],
        PH: ["Manila"],
        MY: ["Kuala_Lumpur"],
        TW: ["Taipei"],
        IL: ["Jerusalem", "Tel_Aviv"],
        SA: ["Riyadh"],
        QA: ["Doha"],
        KW: ["Kuwait"],
        BH: ["Bahrain"],
        OM: ["Muscat"],
        YE: ["Aden"],
        IQ: ["Baghdad"],
        IR: ["Tehran"],
        AF: ["Kabul"],
        PK: ["Karachi", "Islamabad"],
        BD: ["Dhaka"],
        LK: ["Colombo"],
        NP: ["Kathmandu"],
        BT: ["Thimphu"],
        MM: ["Yangon", "Rangoon"],
        LA: ["Vientiane"],
        KH: ["Phnom_Penh"],
        VN: ["Ho_Chi_Minh", "Hanoi"],
        MN: ["Ulaanbaatar"],
        KZ: ["Almaty", "Aqtobe"],
        UZ: ["Tashkent"],
        TJ: ["Dushanbe"],
        KG: ["Bishkek"],
      },
      Australia: {
        AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Darwin", "Hobart", "Canberra"],
      },
      Pacific: {
        AU: ["Hobart"],
        NZ: ["Auckland", "Wellington", "Christchurch"],
        FJ: ["Fiji"],
        PG: ["Port_Moresby"],
        NC: ["Noumea"],
      },
      Africa: {
        EG: ["Cairo"],
        ZA: ["Johannesburg"],
        NG: ["Lagos"],
        KE: ["Nairobi"],
        MA: ["Casablanca"],
        ET: ["Addis_Ababa"],
        GH: ["Accra"],
        TZ: ["Dar_es_Salaam"],
        UG: ["Kampala"],
        RW: ["Kigali"],
        DZ: ["Algiers"],
        TN: ["Tunis"],
        LY: ["Tripoli"],
        SD: ["Khartoum"],
        SN: ["Dakar"],
        CI: ["Abidjan"],
        AO: ["Luanda"],
        ZM: ["Lusaka"],
        ZW: ["Harare"],
        BW: ["Gaborone"],
        MZ: ["Maputo"],
        MG: ["Antananarivo"],
        MU: ["Port_Louis"],
      },
    };

    const continentMap = continentCountryMap[continent];
    if (continentMap) {
      for (const [country, cities] of Object.entries(continentMap)) {
        if (cities.some((c) => city.includes(c) || city === c)) {
          return country;
        }
      }
    }
  }

  // Log missing timezone for debugging
  if (typeof window !== "undefined") {
    missingTimezones.add(timeZone);
    // Log summary after a delay to collect all missing timezones
    if (!hasLoggedSummary) {
      setTimeout(() => {
        if (missingTimezones.size > 0) {
          hasLoggedSummary = true;
          const sorted = Array.from(missingTimezones).sort();
          console.group(`🌍 Missing flags for ${missingTimezones.size} timezones:`);
          sorted.forEach((tz) => console.log(`  - ${tz}`));
          console.groupEnd();
        }
      }, 3000);
    }
  }

  return null;
}
